### ISSUE TITLE
Consider using Forgelin

### ISSUE THREAD

**Issue by marvin-roesch** [Emberwalker/Thumpcord#7]
Hi there, I'm currently looking through mod projects that use Kotlin as their language of choice. I see that your mod shades the Kotlin standard library itself, while at least relocating it. You might want to consider using [Forgelin](https://github.com/shadowfacts/Forgelin/) instead. It gives you access to some more libraries than just the Kotlin standard library and does so without bloating your own mod JAR. Additionally, Kotlin doesn't always like being relocated (especially if you potentially end up shipping the reflection library as well), so going with Forgelin instead is the optimal route for keeping compatibility with other mods written in Kotlin.

**Comment by lopcode** [comment]
Thanks for the suggestion. I actually wrote some of Forgelin: https://github.com/Emberwalker/Forgelin/blob/master/src/main/kotlin/io/drakon/forge/kotlin/KotlinAdapter.kt#L20

The problem is that you end up with similar problems regarding versions of Kotlin, and I don't want to be bound by the version shipped in a different mod.

By relocating my copy on the classpath there are no interoperability problems with other mods, and I'm happy dealing with my own cross-mod communication problems as a cost for that (Thump actually uses "plain" Java reflection to detect plugins like Thumpcord).

There are potential solutions for embedding and depending on different versions of the Kotlin runtime, but I'm too busy to look at them at the moment, and the status quo seems fine.
